services:
  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${PORT_BD}:5432"
    volumes:
      - /bd_data:/var/lib/postgresql/data

  backend:
    build: ./ol-software-backend
    container_name: nest_backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
    ports:
      - "${PORT_BACKEND}:5000"
    command: ["sh", "-c", "npx prisma migrate deploy && node dist/prisma/seed -- all && node dist/src/main"]
    env_file:
      - .env 

  frontend:
    build: ./ol-software-frontend
    container_name: next_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "${PORT_FRONTEND}:3000"

